### PR TITLE
Updated Stripe DTOs to match 2015-10-13 API

### PR DESCRIPTION
**Pull request by jklemmack**
Changes were mostly in upgrading from 'Count' / 'Offset' style paging to 'Limit' / 'StartingAfter' / 'EndingBefore', per the [documentation](https://stripe.com/docs/api#pagination).  As-is, 100% of existing unit tests pass.

There was an issue with some `GET` requests to include the total count of results for some entities.  The API specifically requires `?include[]=total_count` using the bracketed identifier to denote an array.  Not including the brackets results in a failure response from Stripe.  The only way I can think of to send that is to explicitly override how the include parameter is serialized.  I hacked in something in the [base `Send`](https://github.com/ServiceStack/Stripe/compare/master...jklemmack:master#diff-5fb3f0e3e392314a7e4eb4f35eee1694R490) method, but I'm not too happy with it.

### CODE REVIEW

**Comment by mythz** [comment]
If they were `[DataContract]` DTO's you could use an alias:

```csharp
[DataMember(Name = "include[]")]
public string[] Include { get; set; }
```

Adding a QueryString inside a Route path isn't a good solution it promotes bad practice and likely will cause issues in the future as it's expected to only contain a path info. 

```csharp
[Route("/customers/{CustomerId}/sources?object=card&include[]=total_count")]
public class GetStripeCustomerCards : IGet, IReturn<StripeCollection<StripeCard>>
{
    public string CustomerId { get; set; }
    public int? Limit { get; set; }
    public string StartingAfter { get; set; }
    public string EndingBefore { get; set; }
}
```

I'll need to find some time to look at this to find a better solution. Using something like computed properties with an alias as above would be preferred here.

**Comment by jklemmack** [comment]
Yeah, the journey took me to putting query string params in the [Route], but I realized quickly that was begging for trouble.  That should have been overriden in a subsequent commit on the PR line and not be part of the "lines changed".

I suggest I / you / we also add in unit tests to cover at least SOME of the paging scenarios.  It'll be hard to reliably reproduce some things (like listing all Customers), but listing all Cards for a customer should be doable.

**Comment by mythz** [comment]
Hi Johann,

FYI I've added a new `IUrlFilter` interface to allow Request DTO's to customize the url further so all the logic about what's generated is encapsulated in the class: https://github.com/ServiceStack/Stripe/commit/2a68bb7d1460dbc4d4fe05fa88f62979685f677e

I've also switched to using the new `SERVICESTACK_LICENSE` [Environment Variable registration option](https://servicestack.net/download#register) for my projects as it's much easier to manage since it only needs to be declared once and don't have to worry about it getting checked into a public repo.

This change is now available from v4.0.51+ that's [now on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by jklemmack** [comment]
Oh, nice.  I was thinking about some of the changes I made, and I realized
that Stripe supports explicit back versioning of the API version in
requests.  In the spirit of SS's built-in backwards compatibility of DTOs,
some of the "deprecated" properties might still be included.  It'd be up to
the implementer to use the right properties though, so I'm not sure if we
want to give people that much opportunity to harm themselves.

Johann

Hi Johann,

FYI I've added a new IUrlFilter interface to allow Request DTO's to
customize the url further so all the logic about what's generated is
encapsulated in the class: 2a68bb7
<https://github.com/ServiceStack/Stripe/commit/2a68bb7d1460dbc4d4fe05fa88f62979685f677e>

I've also switched to using the new SERVICESTACK_LICENSE Environment
Variable registration option <https://servicestack.net/download#register>
for my projects as it's much easier to manage since it only needs to be
declared once and don't have to worry about it getting checked into a
public repo.

This change is now available from v4.0.51+ that's now on MyGet
<https://github.com/ServiceStack/ServiceStack/wiki/MyGet>.

—
Reply to this email directly or view it on GitHub
<https://github.com/ServiceStack/Stripe/pull/22#issuecomment-163825499>.

**Pull request merged**
